In [1]:
import numpy as np
import pandas as pd

# Response

In [3]:
pd.read_csv('pdx/response.csv')

,Model,Treatment,Treatment target,Treatment type,BestResponse,Day_BestResponse,BestAvgResponse,Day_BestAvgResponse,TimeToDouble,Day_Last,ResponseCategory
0,X-007,BGJ398,FGFR,single,396.5,11,220.5,11,4.0,11,PD
1,X-007,BKM120,"PIK3CA,PIK3CB,PIK3CG,PIK3CD,panPI3K",single,189.1,14,77.1,11,6.2,14,PD
2,X-007,BYL719,PIK3CA,single,303.7,11,196.2,11,4.0,11,PD
3,X-007,BYL719 + HSP990,"PIK3CA,HSP90",combo,-12.7,9,8.7,16,28.0,30,SD-->PD
4,X-007,BYL719 + LJM716,"PIK3CA,ERBB3,ERBB3,PIK3CA",combo,47.9,20,40.6,13,22.8,30,PD
...,...,...,...,...,...,...,...,...,...,...,...
4753,X-6047,binimetinib,"MAP2K1,MAP2K2,MAPK",single,531.2,14,185.6,11,4.0,14,PD
4754,X-6047,paclitaxel,Tubulin,single,125.1,21,6.0,12,18.3,31,PD
4755,X-6047,tamoxifen,ESR1,single,158.7,21,31.7,12,15.3,31,PD
4756,X-6047,trastuzumab,ERBB2,single,402.2,21,55.8,11,8.8,21,PD
4757,X-6047,untreated,"UNKNOWN,Untreated",single,405.4,14,126.3,11,4.7,14,PD

# Expression

In [6]:
pd.read_csv('pdx/rnaseq.csv', index_col='Sample')

,X-1004,X-1008,X-1027,X-1095,X-1119,X-1156,X-1167,X-1169,X-1172,X-1173,...,X-5713,X-5717,X-5727,X-5739,X-5808,X-5959,X-5974,X-5975,X-6030,X-6047
Sample,,,,,,,,,,,,,,,,,,,,,
A1BG,2.75,8.97,0.14,0.13,0.08,17.52,0.18,0.41,0.08,0.00,...,21.24,0.46,18.70,0.00,8.30,14.41,5.09,6.35,0.09,3.22
A1BG-AS1,2.48,3.25,0.00,0.00,0.00,6.52,0.00,0.00,0.00,0.00,...,15.21,0.09,3.42,0.00,8.30,8.36,3.71,4.52,0.00,3.24
A1CF,0.02,0.03,1.30,2.83,2.87,0.72,3.41,0.01,1.84,2.96,...,0.01,0.45,0.00,0.01,0.00,0.00,0.02,0.03,4.63,0.02
A2LD1,4.87,0.81,6.45,4.94,11.07,0.87,3.28,0.32,0.61,7.10,...,1.33,2.51,2.67,3.13,0.44,2.96,0.00,1.99,2.57,1.50
A2M,0.01,71.17,0.00,3.69,0.00,58.16,0.00,0.02,94.12,0.02,...,463.32,0.04,33.35,0.00,254.97,41.52,2.32,0.00,0.00,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,12.84,4.19,0.00,0.07,0.00,3.19,0.00,0.09,3.58,0.00,...,0.11,0.08,0.00,0.60,0.05,0.01,3.92,7.71,0.01,0.42
ZYG11B,10.70,10.37,2.88,2.05,3.04,11.95,5.87,4.97,5.02,3.48,...,12.50,3.67,8.90,3.34,11.31,8.97,6.06,12.17,4.46,1.86
ZYX,38.28,196.29,86.79,37.81,123.66,132.39,70.61,112.46,7.68,193.31,...,55.83,127.44,95.28,159.87,68.09,17.91,36.37,10.35,68.67,57.80
ZZEF1,4.38,6.60,3.83,3.34,6.33,2.65,15.52,8.12,4.61,7.21,...,7.72,5.94,3.96,5.04,3.13,9.14,5.60,10.48,6.51,7.08
ZZZ3,22.00,8.58,8.91,8.16,8.08,12.68,13.00,12.26,16.80,9.96,...,14.36,14.92,7.09,13.47,17.04,14.12,12.55,6.35,17.57,24.57

# Copy Number

In [9]:
pd.read_csv('pdx/cn.csv', index_col='Sample')

,X-1004,X-1008,X-1027,X-1095,X-1119,X-1156,X-1167,X-1169,X-1172,X-1173,...,X-5694,X-5696,X-5713,X-5717,X-5727,X-5739,X-5808,X-5959,X-5975,X-6047
Sample,,,,,,,,,,,,,,,,,,,,,
ArmLevelCNScore,0.56,0.58,0.43,0.46,0.33,0.65,0.36,0.31,0.50,0.42,...,0.47,0.67,0.62,0.43,0.63,0.58,0.49,0.59,0.59,0.61
FocalCNScore,0.53,0.54,0.08,0.15,0.03,0.20,0.07,0.11,0.22,0.08,...,0.12,0.13,0.29,0.43,0.35,0.20,0.14,0.09,0.42,0.27
A1BG,2.58,1.60,2.17,2.08,2.00,3.94,2.04,11.39,2.17,2.01,...,2.08,2.10,2.14,2.95,2.06,2.07,1.99,2.07,1.43,2.03
A1BG-AS1,2.58,1.60,2.17,2.08,2.00,3.94,2.04,11.39,2.17,2.01,...,2.08,2.10,2.14,2.95,2.06,2.07,1.99,2.07,1.43,2.03
A1CF,2.87,2.97,2.01,2.06,2.10,1.58,2.01,1.64,1.89,1.99,...,2.04,0.97,1.58,2.08,1.95,1.92,1.54,1.28,1.33,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,4.47,2.01,1.99,1.96,2.01,2.31,2.03,2.08,1.93,1.97,...,2.03,1.52,2.60,2.11,2.06,1.65,3.41,2.00,3.29,1.42
ZYG11B,4.47,1.68,1.99,1.96,2.01,2.31,2.03,2.08,1.93,1.97,...,2.03,1.52,2.60,2.11,2.06,1.65,3.41,2.00,3.29,1.42
ZYX,3.05,2.55,2.11,2.06,2.11,2.64,2.03,2.19,3.05,2.69,...,3.07,2.04,1.88,1.52,2.28,2.79,2.03,1.29,2.77,2.17
ZZEF1,1.68,2.00,2.03,1.99,2.01,1.58,2.00,1.57,1.35,1.99,...,2.03,1.04,2.83,1.58,1.02,1.44,1.49,2.71,1.48,2.00
ZZZ3,3.94,1.41,2.03,1.97,2.03,2.23,2.00,2.08,2.08,1.97,...,2.01,1.54,1.99,2.11,1.00,1.58,2.35,2.00,0.68,2.14

# Mutation? Only one sample, maybe not so good.

In [11]:
tmp = pd.read_csv('pdx/mut_and_cn2.csv')
tmp

      Sample    Gene    Entrez  Category      Details
0     X-5627    A1BG       1.0  MutNovel   S30G,1.000
1     X-5627   ABCD1     215.0    Del0.8         0.73
2     X-5627   ACOT1  641371.0    Del0.8         0.74
3     X-5627   ACSL4    2182.0    Del0.8         0.72
4     X-5627   ACTA2      59.0    Del0.8         0.24
...      ...     ...       ...       ...          ...
1108  X-5627  ZNF793  390927.0      Amp5         5.06
1109  X-5627  ZNF829  374899.0      Amp5         5.06
1110  X-5627  ZNF850  342892.0      Amp5         5.06
1111  X-5627  ZSWIM7  125150.0      Amp5         5.24
1112  X-5627   ZWINT   11130.0  MutNovel  Q157R,1.000

[1113 rows x 5 columns]

In [12]:
tmp.Category.unique()

array(['MutNovel', 'Del0.8', 'MutKnownFunctional', 'Amp5',
       'MutLikelyFunctional'], dtype=object)

- **MutNovel**: A new mutation that has not been previously reported.
- **Del0.8**: A reduction in copy number (deletion), indicating a decrease from the normal copy number of 2 to 0.8.
- **MutKnownFunctional**: A mutation that has been reported before and confirmed to have functional effects.
- **Amp5**: An increase in copy number (amplification), indicating an increase in copy number up to 5.
- **MutLikelyFunctional**: A mutation believed to have functional effects, although it has not yet been fully confirmed.

In [14]:
tmp.pivot_table(index='Gene', columns='Sample', values='Category', aggfunc='first')

Sample    X-5627
Gene
A1BG    MutNovel
ABCD1     Del0.8
ACOT1     Del0.8
ACSL4     Del0.8
ACTA2     Del0.8
...          ...
ZNF793      Amp5
ZNF829      Amp5
ZNF850      Amp5
ZSWIM7      Amp5
ZWINT   MutNovel

[1054 rows x 1 columns]